<div class="hero-unit">
    <h1>Hero</h1>
</div>

<hr>

<div class="row">
    <div class="span4">
        <h2>Title</h2>
        <p>data data data data</p>
        <p><a class="btn btn-success">Link &raquo;</a></p>
    </div>

    <div class="span4">
        <h2>Title</h2>
        <p>data data data data</p>
        <p><a class="btn btn-success">Link &raquo;</a></p>
    </div>

   <div class="span4">
        <h2>Title</h2>
        <p>data data data data</p>
        <p><a class="btn btn-success">Link &raquo;</a></p>
    </div>
</div>