<div class="hero-unit">
    <h1>Welcome to PIMS</h1>
</div>

<hr>

<div class="row">
    <div class="span4">
        <h2>Record Visit</h2>
        <p></p>
        <p><a class="btn btn-success" href="<?php echo $this->url('visit', array( 
        'action'=>'index'));?>">Record Visit &raquo;</a></p>
    </div>

    <div class="span4">
        <h2>Manage Subjects</h2>
        <p></p>
        <p><a class="btn btn-success" href="<?php echo $this->url('subject', array( 
        'action'=>'index'));?>">Manage Subjects &raquo;</a></p>
    </div>

   <div class="span4">
        <h2>Manage Panels</h2>
        <p></p>
        <p><a class="btn btn-success" href="<?php echo $this->url('panel', array( 
        'action'=>'index'));?>">Manage Panels &raquo;</a></p>
    </div>
</div>

<hr>

<div class="row">
    <div class="span4">
        <h2>Manage Rules</h2>
        <p>This area will be for updating rules about the recording of data. Tolerance burns level. Days of the week for recording.</p>
        <p><a class="btn btn-success" href="<?php echo $this->url('subject', array( 
        'action'=>'index'));?>">Manage Rules &raquo;</a></p>
    </div>

    <div class="span4">
        <h2>Manage Stuff...</h2>
        <p>Manage type tables; hair, eyes, results</p>
        <p><a class="btn btn-success" href="<?php echo $this->url('subject', array( 
        'action'=>'index'));?>">Manage Stuff... &raquo;</a></p>
    </div>

    <div class="span4">
        <h2>Finalize Visits</h2>
        <p>Admin user can review and finalize a visit.</p>
        <p><a class="btn btn-success" href="<?php echo $this->url('visit', array( 
        'action'=>'index'));?>">Finalize Visits &raquo;</a></p>
    </div>
</div>
